### ISSUE TITLE
Higher level API for automatic navmesh generation

### ISSUE THREAD

**Issue by Shatur** [vleue/vleue_navigator#15]
I suggest adding a higher level API under a feature that would automatically tile the world and generate the navigation meshes  automatically from meshes or rapier colliders for entities with special marker-component. And when any new object spawns / despawns it regenerates the navigation mesh for the affected tile.
Similar API is provided by https://github.com/TheGrimsey/oxidized_navigation. It's useful for games with dynamic worlds.

**Comment by night-interactive** [comment]
I would also appreciate such a feature!
