### ISSUE TITLE
Incorrect application of scaling from Transform component when using Avian2D

### ISSUE THREAD

**Issue by taishi-sama** [vleue/vleue_navigator#49]
When navmesh recalculates, scaling factor got applied twice to points of polygons used for building navmesh. 

Example to reproduce: add following line to examples/auto_navmesh_avian2d.rs 
![изображение](https://github.com/user-attachments/assets/648f2995-fe4b-44cd-9610-91f0a4eac2a0)
or replace its content with [auto_navmesh_avian2d.txt](https://github.com/user-attachments/files/16737268/auto_navmesh_avian2d.txt)
Before recalculation:
![auto_navmesh_avian2d_hX8oeXqld9](https://github.com/user-attachments/assets/79498086-1dc5-4dad-b913-d7ea01a464b9)
After recalculation: 
![auto_navmesh_avian2d_ixSz0QvD5o](https://github.com/user-attachments/assets/f906d546-0167-49dd-a252-eb30107530d3)
This problem exists with at least two kinds of polygons, such as cuboids or circles

**Comment by mockersf** [comment]
Thanks for noticing!

as avian2d/3d already applies the scale to the collider, I didn't need to re-apply it again.

This should be fixed in #43
