### ISSUE TITLE
[Question] Is there any way to add a "distance" from obstacle?

### ISSUE THREAD

**Issue by nickydonna** [vleue/vleue_navigator#50]
I'm using the avian3d navmesh generation, and the path is generated from the center of the collider, and they end up crashing to obstacles side. Is there a way to take the size of the collider?

Sorry if this is a bad question, I'm learning about gamedev

**Comment by mockersf** [comment]
Not yet!

What you're looking for is called "agent radius", and I want to support it, but it's not yet done.

For now, a workaround can be to add bigger obstacles than the ones used by avian3d, but it can be painful to keep everything in sync if they are dynamic.

**Comment by nickydonna** [comment]
Awesome!! Thanks! Anything I can do to help?

**Comment by mockersf** [comment]
Yes you can!

So I have two ideas on how to implement agent radius

## First idea: inflate colliders

This can be done in this crate. On the method `ObstacleSource::get_polygon`, add a new parameter `agent_radius`:
https://github.com/vleue/vleue_navigator/blob/efabdedff49ec3114a6d9bc9f221936543bcb7b8/src/obstacles/mod.rs#L18-L26
Then use the radius to inflate the obstacles when getting their polygons. Example with the avian3d `Cuboid` collider: https://github.com/vleue/vleue_navigator/compare/main...agent-radius-avian3d-cuboid
This is mostly straightforward to do for simple colliders like the cuboid, it can get more complex for others.


## Second idea: inflate/deflate polygons before feeding them to triangulation

This can be done in the [`polyanya`](https://github.com/vleue/polyanya) crate. During the transformation from a geo multipolygon to a triangulation, inflate/deflate the polygons depending on if their exterior or interior. Then do their union if needed, and continue to the triangulation.
Last time I tried, I hade issues with speed, stability or platform support. Some crates to do that are fast but not wasm-compatible, some are wasm-compatible but panics sometimes, ...

In my opinion, the second idea will produce nicer results but requires more work. The first idea is a good stop-gap solution , and could even be faster to compute

**Comment by nickydonna** [comment]
I’m not that knowledgeable with rust or navigation, so I can help with the first approach, and we can iterate if that is coolSent from my iPhoneOn 10 Sep 2024, at 9:05 PM, François Mockers ***@***.***> wrote:﻿
Yes you can!
So I have two ideas on how to implement agent radius
First idea: inflate colliders
This can be done in this crate. On the method ObstacleSource::get_polygon, add a new parameter agent_radius:
https://github.com/vleue/vleue_navigator/blob/efabdedff49ec3114a6d9bc9f221936543bcb7b8/src/obstacles/mod.rs#L18-L26
Then use the radius to inflate the obstacles when getting their polygons. Example with the avian3d Cuboid collider: main...agent-radius-avian3d-cuboid
This is mostly straightforward to do for simple colliders like the cuboid, it can get more complex for others.
Second idea: inflate/deflate polygons before feeding them to triangulation
This can be done in the polyanya crate. During the transformation from a geo multipolygon to a triangulation, inflate/deflate the polygons depending on if their exterior or interior. Then do their union if needed, and continue to the triangulation.
Last time I tried, I hade issues with speed, stability or platform support. Some crates to do that are fast but not wasm-compatible, some are wasm-compatible but panics sometimes, ...
In my opinion, the second idea will produce nicer results but requires more work. The first idea is a good stop-gap solution , and could even be faster to compute
