### ISSUE TITLE
Does it support uneven surfaces?

### ISSUE THREAD

**Issue by 0x0539** [vleue/vleue_navigator#63]
The docs say they "assume it constructs a 2d structure."

https://docs.rs/vleue_navigator/latest/src/vleue_navigator/lib.rs.html#129

Does that mean I can only use that fn on a flat mesh? The vertices of the mesh must be coplanar?

**Comment by mockersf** [comment]
it should work with a non-flat mesh, but I haven't tested. the"height" of each vertex according to the transform of the mesh relative to the Z axis will be ignored.

if you need a more complex mesh with overlapping part, it's now possible to have layers as in https://vleue.github.io/vleue_navigator/layers.html
